/* Generated by Yosys 0.8+152 (git sha1 2a8e5bf9, clang 6.0.0-1ubuntu2 -fPIC -Os) */

module top(clk, LED_R, LED_G, LED_B, OK);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  output LED_B;
  output LED_G;
  output LED_R;
  output OK;
  input clk;
  wire \count_cur[0] ;
  wire \count_cur[1] ;
  wire \count_cur[2] ;
  wire \count_cur[3] ;
  wire \count_cur[4] ;
  wire \count_cur[5] ;
  wire \count_cur[6] ;
  wire \count_cur[7] ;
  wire led_g_reg;
  wire \reset_counter[0] ;
  wire \reset_counter[1] ;
  wire \reset_counter[2] ;
  wire \reset_counter[3] ;
  wire \reset_counter[4] ;
  wire \reset_counter[5] ;
  wire \reset_counter[6] ;
  wire \reset_counter[7] ;
  wire resetn;
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h1000)
  ) _075_ (
    .I0(_011_),
    .I1(_023_),
    .I2(_029_),
    .I3(_033_),
    .O(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h96)
  ) _076_ (
    .I0(_023_),
    .I1(\count_cur[1] ),
    .I2(\count_cur[0] ),
    .I3(_072_),
    .O(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h40ff)
  ) _077_ (
    .I0(_011_),
    .I1(_033_),
    .I2(_029_),
    .I3(resetn),
    .O(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'hca)
  ) _078_ (
    .I0(_036_),
    .I1(_037_),
    .I2(_023_),
    .I3(_072_),
    .O(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'hf8)
  ) _079_ (
    .I0(_039_),
    .I1(_038_),
    .I2(resetn),
    .I3(_072_),
    .O(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8000)
  ) _080_ (
    .I0(\reset_counter[3] ),
    .I1(\reset_counter[2] ),
    .I2(\reset_counter[1] ),
    .I3(\reset_counter[0] ),
    .O(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h8000)
  ) _081_ (
    .I0(\reset_counter[7] ),
    .I1(\reset_counter[6] ),
    .I2(\reset_counter[5] ),
    .I3(\reset_counter[4] ),
    .O(_039_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:40" *)
  SB_LUT4 #(
    .LUT_INIT(2'h1)
  ) _082_ (
    .I0(resetn),
    .I1(_072_),
    .I2(_072_),
    .I3(_072_),
    .O(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:40" *)
  SB_LUT4 #(
    .LUT_INIT(2'h1)
  ) _083_ (
    .I0(\reset_counter[1] ),
    .I1(_072_),
    .I2(_072_),
    .I3(_072_),
    .O(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:40" *)
  SB_LUT4 #(
    .LUT_INIT(2'h1)
  ) _084_ (
    .I0(\count_cur[1] ),
    .I1(_072_),
    .I2(_072_),
    .I3(_072_),
    .O(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:40" *)
  SB_LUT4 #(
    .LUT_INIT(2'h1)
  ) _085_ (
    .I0(\count_cur[0] ),
    .I1(_072_),
    .I2(_072_),
    .I3(_072_),
    .O(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'h01)
  ) _086_ (
    .I0(_016_),
    .I1(_013_),
    .I2(_012_),
    .I3(_072_),
    .O(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:40" *)
  SB_LUT4 #(
    .LUT_INIT(2'h1)
  ) _087_ (
    .I0(\count_cur[2] ),
    .I1(_072_),
    .I2(_072_),
    .I3(_072_),
    .O(_042_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:40" *)
  SB_LUT4 #(
    .LUT_INIT(2'h1)
  ) _088_ (
    .I0(\count_cur[4] ),
    .I1(_072_),
    .I2(_072_),
    .I3(_072_),
    .O(_043_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:40" *)
  SB_LUT4 #(
    .LUT_INIT(2'h1)
  ) _089_ (
    .I0(\count_cur[5] ),
    .I1(_072_),
    .I2(_072_),
    .I3(_072_),
    .O(_044_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:40" *)
  SB_LUT4 #(
    .LUT_INIT(2'h1)
  ) _090_ (
    .I0(\count_cur[3] ),
    .I1(_072_),
    .I2(_072_),
    .I3(_072_),
    .O(_045_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:40" *)
  SB_LUT4 #(
    .LUT_INIT(2'h1)
  ) _091_ (
    .I0(\count_cur[6] ),
    .I1(_072_),
    .I2(_072_),
    .I3(_072_),
    .O(_046_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:40" *)
  SB_LUT4 #(
    .LUT_INIT(2'h1)
  ) _092_ (
    .I0(\count_cur[7] ),
    .I1(_072_),
    .I2(_072_),
    .I3(_072_),
    .O(_047_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:47|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _093_ (
    .CI(_041_),
    .CO(_048_),
    .I0(_073_),
    .I1(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:47|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _094_ (
    .CI(_048_),
    .CO(_049_),
    .I0(_072_),
    .I1(_042_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:47|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _095_ (
    .CI(_049_),
    .CO(_050_),
    .I0(_073_),
    .I1(_045_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:47|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _096_ (
    .CI(_050_),
    .CO(_051_),
    .I0(_073_),
    .I1(_043_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'hca)
  ) _097_ (
    .I0(_034_),
    .I1(_035_),
    .I2(_023_),
    .I3(_072_),
    .O(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:47|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _098_ (
    .CI(_051_),
    .CO(_052_),
    .I0(_072_),
    .I1(_044_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:47|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _099_ (
    .CI(_052_),
    .CO(_053_),
    .I0(_073_),
    .I1(_046_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:47|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _100_ (
    .CI(_053_),
    .CO(_000_),
    .I0(_072_),
    .I1(_047_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:22|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _101_ (
    .I0(_072_),
    .I1(_073_),
    .I2(\reset_counter[0] ),
    .I3(_072_),
    .O(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:22|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _102_ (
    .CI(\reset_counter[0] ),
    .CO(_054_),
    .I0(_072_),
    .I1(\reset_counter[1] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:22|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _103_ (
    .I0(_072_),
    .I1(_072_),
    .I2(\reset_counter[2] ),
    .I3(_054_),
    .O(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:22|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _104_ (
    .CI(_054_),
    .CO(_055_),
    .I0(_072_),
    .I1(\reset_counter[2] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:22|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _105_ (
    .I0(_072_),
    .I1(_072_),
    .I2(\reset_counter[3] ),
    .I3(_055_),
    .O(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:22|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _106_ (
    .CI(_055_),
    .CO(_056_),
    .I0(_072_),
    .I1(\reset_counter[3] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:22|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _107_ (
    .I0(_072_),
    .I1(_072_),
    .I2(\reset_counter[4] ),
    .I3(_056_),
    .O(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'hca)
  ) _108_ (
    .I0(_026_),
    .I1(_027_),
    .I2(_023_),
    .I3(_072_),
    .O(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:22|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _109_ (
    .CI(_056_),
    .CO(_057_),
    .I0(_072_),
    .I1(\reset_counter[4] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:22|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _110_ (
    .I0(_072_),
    .I1(_072_),
    .I2(\reset_counter[5] ),
    .I3(_057_),
    .O(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:22|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _111_ (
    .CI(_057_),
    .CO(_058_),
    .I0(_072_),
    .I1(\reset_counter[5] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:22|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _112_ (
    .I0(_072_),
    .I1(_072_),
    .I2(\reset_counter[6] ),
    .I3(_058_),
    .O(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:22|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _113_ (
    .CI(_058_),
    .CO(_059_),
    .I0(_072_),
    .I1(\reset_counter[6] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:22|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _114_ (
    .I0(_072_),
    .I1(_072_),
    .I2(\reset_counter[7] ),
    .I3(_059_),
    .O(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:33|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _115_ (
    .I0(_072_),
    .I1(_073_),
    .I2(\count_cur[0] ),
    .I3(_072_),
    .O(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:33|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _116_ (
    .CI(\count_cur[0] ),
    .CO(_060_),
    .I0(_072_),
    .I1(\count_cur[1] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:33|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _117_ (
    .I0(_072_),
    .I1(_072_),
    .I2(\count_cur[2] ),
    .I3(_060_),
    .O(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:33|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _118_ (
    .CI(_060_),
    .CO(_061_),
    .I0(_072_),
    .I1(\count_cur[2] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'hca)
  ) _119_ (
    .I0(_024_),
    .I1(_025_),
    .I2(_023_),
    .I3(_072_),
    .O(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:33|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _120_ (
    .I0(_072_),
    .I1(_072_),
    .I2(\count_cur[3] ),
    .I3(_061_),
    .O(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:33|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _121_ (
    .CI(_061_),
    .CO(_062_),
    .I0(_072_),
    .I1(\count_cur[3] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:33|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _122_ (
    .I0(_072_),
    .I1(_072_),
    .I2(\count_cur[4] ),
    .I3(_062_),
    .O(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:33|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _123_ (
    .CI(_062_),
    .CO(_063_),
    .I0(_072_),
    .I1(\count_cur[4] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:33|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _124_ (
    .I0(_072_),
    .I1(_072_),
    .I2(\count_cur[5] ),
    .I3(_063_),
    .O(_031_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:33|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _125_ (
    .CI(_063_),
    .CO(_064_),
    .I0(_072_),
    .I1(\count_cur[5] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:33|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _126_ (
    .I0(_072_),
    .I1(_072_),
    .I2(\count_cur[6] ),
    .I3(_064_),
    .O(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:33|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _127_ (
    .CI(_064_),
    .CO(_065_),
    .I0(_072_),
    .I1(\count_cur[6] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:33|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _128_ (
    .I0(_072_),
    .I1(_072_),
    .I2(\count_cur[7] ),
    .I3(_065_),
    .O(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:35|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _129_ (
    .I0(_072_),
    .I1(\count_cur[0] ),
    .I2(_072_),
    .I3(_073_),
    .O(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:52" *)
  SB_LUT4 #(
    .LUT_INIT(16'h0100)
  ) _130_ (
    .I0(_015_),
    .I1(_010_),
    .I2(_014_),
    .I3(resetn),
    .O(_033_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:35|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _131_ (
    .CI(\count_cur[0] ),
    .CO(_066_),
    .I0(\count_cur[1] ),
    .I1(_073_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:35|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _132_ (
    .I0(_072_),
    .I1(\count_cur[2] ),
    .I2(_073_),
    .I3(_066_),
    .O(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:35|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _133_ (
    .CI(_066_),
    .CO(_067_),
    .I0(\count_cur[2] ),
    .I1(_073_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:35|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _134_ (
    .I0(_072_),
    .I1(\count_cur[3] ),
    .I2(_073_),
    .I3(_067_),
    .O(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:35|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _135_ (
    .CI(_067_),
    .CO(_068_),
    .I0(\count_cur[3] ),
    .I1(_073_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:35|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _136_ (
    .I0(_072_),
    .I1(\count_cur[4] ),
    .I2(_073_),
    .I3(_068_),
    .O(_030_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:35|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _137_ (
    .CI(_068_),
    .CO(_069_),
    .I0(\count_cur[4] ),
    .I1(_073_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:35|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _138_ (
    .I0(_072_),
    .I1(\count_cur[5] ),
    .I2(_073_),
    .I3(_069_),
    .O(_032_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:35|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _139_ (
    .CI(_069_),
    .CO(_070_),
    .I0(\count_cur[5] ),
    .I1(_073_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:35|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _140_ (
    .I0(_072_),
    .I1(\count_cur[6] ),
    .I2(_073_),
    .I3(_070_),
    .O(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'hca)
  ) _141_ (
    .I0(_031_),
    .I1(_032_),
    .I2(_023_),
    .I3(_072_),
    .O(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:35|/usr/local/bin/../share/yosys/ice40/arith_map.v:47" *)
  SB_CARRY _142_ (
    .CI(_070_),
    .CO(_071_),
    .I0(\count_cur[6] ),
    .I1(_073_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:35|/usr/local/bin/../share/yosys/ice40/arith_map.v:53" *)
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) _143_ (
    .I0(_072_),
    .I1(\count_cur[7] ),
    .I2(_073_),
    .I3(_071_),
    .O(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:27|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFFSS _144_ (
    .C(clk),
    .D(_010_),
    .Q(\count_cur[0] ),
    .S(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:27|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFFSR _145_ (
    .C(clk),
    .D(_011_),
    .Q(\count_cur[1] ),
    .R(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:27|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFFSR _146_ (
    .C(clk),
    .D(_012_),
    .Q(\count_cur[2] ),
    .R(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:27|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFFSR _147_ (
    .C(clk),
    .D(_013_),
    .Q(\count_cur[3] ),
    .R(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:27|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFFSR _148_ (
    .C(clk),
    .D(_014_),
    .Q(\count_cur[4] ),
    .R(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:27|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFFSR _149_ (
    .C(clk),
    .D(_015_),
    .Q(\count_cur[5] ),
    .R(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:27|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFFSR _150_ (
    .C(clk),
    .D(_016_),
    .Q(\count_cur[6] ),
    .R(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:27|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFFSR _151_ (
    .C(clk),
    .D(_017_),
    .Q(\count_cur[7] ),
    .R(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'hac)
  ) _152_ (
    .I0(_022_),
    .I1(_021_),
    .I2(_023_),
    .I3(_072_),
    .O(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:27|/usr/local/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _153_ (
    .C(clk),
    .D(_018_),
    .E(_020_),
    .Q(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:27|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _154_ (
    .C(clk),
    .D(_000_),
    .Q(led_g_reg)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:21|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _155_ (
    .C(clk),
    .D(_001_),
    .Q(\reset_counter[0] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:21|/usr/local/bin/../share/yosys/ice40/cells_map.v:8" *)
  SB_DFFE _156_ (
    .C(clk),
    .D(_002_),
    .E(\reset_counter[0] ),
    .Q(\reset_counter[1] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:21|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _157_ (
    .C(clk),
    .D(_003_),
    .Q(\reset_counter[2] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:21|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _158_ (
    .C(clk),
    .D(_004_),
    .Q(\reset_counter[3] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:21|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _159_ (
    .C(clk),
    .D(_005_),
    .Q(\reset_counter[4] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:21|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _160_ (
    .C(clk),
    .D(_006_),
    .Q(\reset_counter[5] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:21|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _161_ (
    .C(clk),
    .D(_007_),
    .Q(\reset_counter[6] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:21|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _162_ (
    .C(clk),
    .D(_008_),
    .Q(\reset_counter[7] )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/local/bin/../share/yosys/ice40/cells_map.v:48" *)
  SB_LUT4 #(
    .LUT_INIT(8'hca)
  ) _163_ (
    .I0(_028_),
    .I1(_030_),
    .I2(_023_),
    .I3(_072_),
    .O(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "simulate.v:21|/usr/local/bin/../share/yosys/ice40/cells_map.v:2" *)
  SB_DFF _164_ (
    .C(clk),
    .D(_009_),
    .Q(resetn)
  );
  assign _072_ = 1'h0;
  assign _073_ = 1'h1;
  assign _074_ = 1'hx;
  assign OK = resetn;
  assign LED_R = _072_;
  assign LED_G = led_g_reg;
  assign LED_B = _072_;
endmodule
