module pll (
    input i_clk,
    output o_clk
);
  // Generated by icepll -i 12 -o 24
  //
  // F_PLLIN:    12.000 MHz (given)
  // F_PLLOUT:   24.000 MHz (requested)
  // F_PLLOUT:   24.000 MHz (achieved)
  // 
  // FEEDBACK: SIMPLE
  // F_PFD:   12.000 MHz
  // F_VCO:  768.000 MHz
  // 
  // DIVR:  0 (4'b0000)
  // DIVF: 63 (7'b0111111)
  // DIVQ:  5 (3'b101)
  // 
  // FILTER_RANGE: 1 (3'b001)
  
  // Phase locked loop
  SB_PLL40_CORE #(
    .FEEDBACK_PATH("SIMPLE"),
    .PLLOUT_SELECT("GENCLK"),
    .DIVR(4'b0000),
    .DIVF(7'b0111111),
    .DIVQ(3'b101),
    .FILTER_RANGE(3'b101)
  ) SB_PLL40_PAD_inst (
    .RESETB(1'b1),
    .BYPASS(1'b0),
    .REFERENCECLK(i_clk),
    .PLLOUTCORE(o_clk)
  );

endmodule
